AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  first-workflow

  Sample SAM Template for first-workflow

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'StateMachineIAMRolePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 'lambda:InvokeFunction'
                Resource:
                  - !GetAtt PurchaseOrderFunction.Arn
                  - !GetAtt FundFunction.Arn

  HelloWorldStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: state_machine/workflow.asl.json
      Role: !GetAtt HelloWorldStateMachineRole.Arn
      DefinitionSubstitutions:
        PurchaseOrderFunctionArn: !GetAtt PurchaseOrderFunction.Arn
        FundsFunctionArn: !GetAtt FundFunction.Arn

  PurchaseOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: purchase_order/
      Handler: app.lambda_handler
      Runtime: python3.8

  FundFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: funds/
      Handler: app.lambda_handler
      Runtime: python3.8

Outputs:
  PurchaseOrderFunction:
    Description: 'Purchase Order Lambda Function ARN'
    Value: !GetAtt PurchaseOrderFunction.Arn
  FundFunction:
    Description: 'Fund Lambda Function ARN'
    Value: !GetAtt FundFunction.Arn
  PurchaseOrderFunctionIamRole:
    Description: 'Implicit IAM Role created for Purchase Order function'
    Value: !GetAtt PurchaseOrderFunctionRole.Arn
  FundFunctionIamRole:
    Description: 'Implicit IAM Role created for Fund function'
    Value: !GetAtt FundFunctionRole.Arn
  HelloWorldStateMachine:
    Description: 'Hello World State Machine ARN'
    Value: !Ref HelloWorldStateMachine
